Data Layer Setup
Vanshbajaj/Practical-Assignment pull request #10
Opened 2024-10-22 12:58 UTC by Vanshbajaj

1.Steup Data Layer
2.Add All Things That Required for Data Layer

2024-10-23 08:52 UTC, shubhamsinghmutualmobile approved these changes

2024-10-23 08:52 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/network/DataModule.kt
> +object DataModule {
No `@InstallIn`?

2024-10-23 08:52 UTC, shubhamsinghmutualmobile commented on gradle/libs.versions.toml
> +dagger = "2.44"
Why downgrade?

2024-10-23 10:31 UTC, shreyansh-mm requested changes

2024-10-23 10:31 UTC, shreyansh-mm commented on .github/workflows/ci.yml
> +
Why do we need it twice?

2024-10-23 10:31 UTC, shreyansh-mm commented on data/build.gradle.kts
> +    id("kotlin-kapt")
We can use KSP with upgraded version of dagger (2.48 and above)

2024-10-23 10:31 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/network/DataModule.kt
> +            .serverUrl("https://rickandmortyapi.com/graphql")
Let's move the URL to a constants file for now

2024-10-23 10:31 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/CharacterDataClass.kt
> +data class CharacterDataClass(
formatting

2024-10-23 11:11 UTC, Vanshbajaj commented on data/src/main/java/com/practical/data/network/DataModule.kt
> +object DataModule {
Using Dagger2

2024-10-23 11:12 UTC, Vanshbajaj commented on gradle/libs.versions.toml
> +dagger = "2.44"
Dagger 2 Was not working so i need downgrade, soon updating to ksp

2024-10-23 11:12 UTC, Vanshbajaj commented on data/src/main/java/com/practical/data/network/DataModule.kt
> +            .serverUrl("https://rickandmortyapi.com/graphql")
Sure

2024-10-23 11:13 UTC, Vanshbajaj commented on data/build.gradle.kts
> +    id("kotlin-kapt")
Sure

2024-10-24 10:21 UTC, shreyansh-mm approved these changes

2024-10-24 10:21 UTC, shreyansh-mm commented on build.gradle.kts
> +   alias(libs.plugins.ksp.plugin) apply  false
alignment

2024-10-24 10:23 UTC, merged