Screen 1
Vanshbajaj/Practical-Assignment pull request #13
Opened 2024-10-28 10:24 UTC by Vanshbajaj

![image](https://github.com/user-attachments/assets/ac3ebab2-a4d4-476c-8b45-d16a90f545e3)
Characters Screen  Completed

2024-10-28 13:04 UTC, shreyansh-mm requested changes

2024-10-28 13:04 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +                    fontSize = 20.sp,
Both these values can be combined into a `TextStyle` which can be added in `Typography` in Theme System.
So create a new one or modify an existing one and use it here instead of `color` and `fontSize` property

2024-10-28 13:04 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +    fun CharacterItem(character: CharacterDataClass) {
This should be a `private` composable

2024-10-28 13:04 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +class CharacterViewModel @Inject constructor(
Currently there is no way for UI to request for updates (pull to refresh), please add a provision for it.

2024-10-29 06:08 UTC, pushpalroygd commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +private fun characterItem(character: CharacterDataClass) {
@Vanshbajaj Can we rename the name `CharacterDataClass` to `CharacterModel` or similar?

2024-10-29 06:10 UTC, pushpalroygd commented
@Vanshbajaj Can we follow this for git commit message styles: https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

2024-10-29 12:00 UTC, shreyansh-mm requested changes

2024-10-29 12:05 UTC, shreyansh-mm requested changes

2024-10-29 12:05 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/Dimens.kt
> +object Dimens {
This is not the right way to implement Dimens

2024-10-29 12:05 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +class CharacterViewModel @Inject constructor(
Currently there is no way for UI to request for updates (pull to refresh), please add a provision for it.

2024-10-29 14:01 UTC, Vanshbajaj commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +class CharacterViewModel @Inject constructor(
Added

2024-10-29 14:48 UTC, Vanshbajaj commented on app/src/main/java/com/practical/assignment/MainActivity.kt
> +                    characterScreen(viewModel)
Added

2024-10-29 14:48 UTC, Vanshbajaj commented on common/src/main/java/com/practical/common/Constants.kt
> +//
Fixed

2024-10-29 14:49 UTC, Vanshbajaj commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +            .padding(Dimens.paddingSmall),
Fixed

2024-10-29 14:49 UTC, Vanshbajaj commented on presentation/src/main/java/com/practical/presentation/Dimens.kt
> +object Ratio{
Fixed

2024-10-30 09:34 UTC, shreyansh-mm requested changes

2024-10-30 09:34 UTC, shreyansh-mm commented on app/src/main/java/com/practical/assignment/AppNavGraph.kt
> +    NavHost(navController, startDestination = "home") {
Let's use type safe navigation

2024-10-30 09:34 UTC, shreyansh-mm commented on app/src/main/res/values/colors.xml
Delete?

2024-10-30 09:34 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +    override suspend fun getCharacters(): List<CharacterModel> {
Use Sealed class to wrap data and show state

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +object CharacterScreen {
Make it private or internal and rename to `CharacterScreenValues`

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +    val dimens = LocalDimens.current
Let's use Extension Variables on MaterialTheme to access dimens

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +    val refreshData = {
This will recompose unnecessarily

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +                items(characters.size) { index ->
add keys if possible to reduce recompositions

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +fun SwipeRefresh(isRefreshing: Boolean, onRefresh: () -> Unit, content: @Composable () -> Unit) {
Use the one found in Jetpack compose foundation

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/ui/theme/Theme.kt
> +val lightDimens = Dimens(
rename to just `dimens`?

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/ui/theme/Theme.kt
> +            }
formatting

2024-10-30 09:34 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +                fontSize = MaterialTheme.typography.headlineSmall.fontSize,
Use typography / TextStyle instead

2024-10-30 11:46 UTC, shubhamsinghmutualmobile approved these changes

2024-10-30 11:46 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/CharacterScreen.kt
> +fun SwipeRefresh(isRefreshing: Boolean, onRefresh: () -> Unit, content: @Composable () -> Unit) {
Why don't you use the [PullRefresh](https://developer.android.com/reference/kotlin/androidx/compose/material/pullrefresh/package-summary) composable that's already available to you via the Material Library?

2024-10-30 11:46 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/ui/theme/Theme.kt
> +val lightDimens = Dimens(
Also, make it `private` since you don't need to promote its access over `LocalDimens`

2024-10-30 11:47 UTC, shubhamsinghmutualmobile commented
> <img alt="Screenshot 2024-10-28 at 3 34 47 PM" width="409" src="https://private-user-images.githubusercontent.com/31435021/380679764-a85fd548-0f2e-448b-ae4f-4a3a06ca3612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODkxMTYsIm5iZiI6MTczMDI4ODgxNiwicGF0aCI6Ii8zMTQzNTAyMS8zODA2Nzk3NjQtYTg1ZmQ1NDgtMGYyZS00NDhiLWFlNGYtNGEzYTA2Y2EzNjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDExNDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NGNkODVmYzA2MzEwZjY2MTdlNWNmMzVkYjEwZTU3ZDBlMzk0ODQwMmQ0MDJhNDA0MDBmN2Q4ODFlZmFlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jZe-okCn_wSr5IYLmOmzlqLdg2dnSz0P7n_jh-I7Yj8">
> 1. Added Characters Screen

Share screenshot of your own app rather than the design

2024-11-04 05:11 UTC, shubhamsinghmutualmobile commented
@Vanshbajaj This is a very big PR. Please break it down into smaller, more easily reviewable chunks.

2024-11-05 10:21 UTC, merged