Screen-1Fixes
Vanshbajaj/Practical-Assignment pull request #14
Opened 2024-10-30 11:43 UTC by Vanshbajaj

Recomposition Fixed
MaterialDimens Added
detekt.yml updated with compose

2024-10-30 11:50 UTC, shubhamsinghmutualmobile commented
Please use `Screen1` its this PR's base branch because this PR does not show only the `fixes` you have worked on, it shows everything including your previous branch's code.

2024-10-30 12:51 UTC, shreyansh-mm requested changes

2024-10-30 12:51 UTC, shreyansh-mm commented on app/src/main/java/com/practical/assignment/AppNavGraph.kt
> +    NavHost(navController, startDestination = Screen.Home.route) {
We can use type safety instead of string identifier

2024-10-30 12:51 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +    override suspend fun getCharacters(): ResultState<List<CharacterModel>> {
Let's use flows

2024-10-30 12:51 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/ResultState.kt
> +sealed class ResultState<out T> {
Either add NoData state or make T nullable

2024-10-30 12:51 UTC, shreyansh-mm commented on gradle/libs.versions.toml
> +detektcompose = "0.4.16+"
Avoid using `+` in dependency versions

2024-10-30 12:51 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreenValues.kt
Change file name to `CharacterScreen`

2024-10-30 12:51 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreenValues.kt
> +            .padding(MaterialDimens.paddingMedium),
Expected Syntax `MaterialTheme.dimens.mediumPadding`

2024-10-30 12:51 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreenValues.kt
> +
Add provision for pull to refresh

2024-10-31 05:35 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/ResultState.kt
> +    data class Success<out T>(val data: T) : ResultState<T>()
You can replace `out T` with just `T` here because you're already using `out` on `ResultState`

2024-10-31 05:36 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/ResultState.kt
> +sealed class ResultState<out T> {
@shreyansh-mm Could you please add a bit more explanation here?

2024-10-31 05:36 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/ResultState.kt
> +sealed class ResultState<out T> {
> Either add NoData state or make T nullable

@shreyansh-mm Could you please add a bit more explanation for this?

2024-10-31 05:37 UTC, shubhamsinghmutualmobile commented on gradle/libs.versions.toml
> +kotlinxSerializationCore = "1.6.2"
I think serialization core uses the same version as `kotlin` 🤔

2024-10-31 05:38 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    val charactersState by viewModel.charactersState.collectAsState()
Prefer using `collectAsStateUsingLifecycle`

2024-10-31 06:09 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    }
Use `if-else` if you have <= 2 conditions. `when` is useful for simplifying greater number of conditions.

2024-10-31 06:09 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +}
This composable isn't adding any value, better to get rid of it

2024-10-31 06:09 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +}
Same with this

2024-10-31 06:09 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +            viewModelScope.launch(Dispatchers.IO) {
Consider [injecting dispatchers](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers) for better testability of ViewModels.

2024-10-31 07:37 UTC, shubhamsinghmutualmobile approved these changes

2024-10-31 10:26 UTC, shreyansh-mm approved these changes

2024-10-31 11:23 UTC, merged