Data and Domain Layer Setup For Screen 2
Vanshbajaj/Practical-Assignment pull request #20
Opened 2024-11-07 11:00 UTC by Vanshbajaj

1. Added Data Layer  Updated RepositoryImpl 
2. And Domain Layer Updated UseCases And Repository
3. Added Request For Screen 2

2024-11-08 05:25 UTC, shreyansh-mm requested changes

2024-11-08 05:25 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/usecases/GetCharactersUseCase.kt
> +    suspend fun getCharacters(id: String): Flow<ResultState<CharacterModel>> {
new use case should be created for this

2024-11-08 05:25 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/repository/CharacterRepository.kt
> +    suspend fun getCharacter(id: String): Flow<ResultState<CharacterModel>>
why is one method suspended and another is not when both are returning flows?

2024-11-08 05:25 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +
Lot of unnecessary new lines, lets get rid of them

2024-11-08 05:25 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +    }
Let's follow one style?
also we can get rid of `.onStart { _charactersState.emit(ResultState.Loading) }` since we are emitting `(ResultState.Loading)` while initializing and setting the same state won't do anything.

2024-11-08 07:22 UTC, shubhamsinghmutualmobile requested changes

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/@IoDispatcher.kt
> +annotation class IoDispatcher
Why do we need this qualifier? Is the DI container providing different variants of CoroutineDispatcher?

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/DispatcherModule.kt
> +}
A better and more generic name for this could be `coroutineDispatcher`.

`Reason`: We are injecting the dispatcher because we want to be able to provide a custom test dispatcher while testing our classes. Since we will not be injecting `IO` dispatchers in tests, therefore writing `ioDispatcher = testDispatcher` makes less sense. Hence, using a more generic term like `coroutineDispatcher` should help.

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Rename this to `coroutineDispatcher` and remove the annotation, read the explanation above.

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/ViewModelFactory.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Rename this to `coroutineDispatcher` and remove the annotation, read the explanation above.

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/ViewModelModule.kt
> +        @IoDispatcher ioDispatcher: CoroutineDispatcher
Rename this to `coroutineDispatcher` and remove the annotation, read the explanation above.

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/practical/presentation/CharacterViewModelTest.kt
> +        viewModel = CharacterViewModel(getCharactersUseCase,getCharacterUseCase, testDispatcher)
Use named parameters wherever possible throughout the codebase. It makes the code clearer/more obvious and it also looks cleaner.

2024-11-08 07:22 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +                emit(ResultState.Success(character))
Avoid using the double bang operator (`!!`) wherever possible.
Rectified example:
```kotlin
...
response.data?.character?.toCharacterModel()?.let { character ->
  emit(ResultState.Success(character))
} ?: run {
  emit(ResultState.Error(Exception("Character data not found!")))
}
...
```

2024-11-08 07:24 UTC, shubhamsinghmutualmobile commented
Also, please fix the CI job(s).

2024-11-11 05:32 UTC, shreyansh-mm requested changes

2024-11-11 05:32 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/CharacterModel.kt
> +    val type: String? = "",
`null` values should be initialized with `null` not empty data.
  Else UI will not know when we actually have data and when we don't.

2024-11-11 05:32 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/CharacterModel.kt
> +    val origin: OriginModel,
should be initialized as `val origin: OriginModel = OriginModel()`

2024-11-11 05:32 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +                val character = response.data?.character?.toCharacterModel()?: CharacterModel(
We updated the Model to fix construction of the object,

2024-11-11 05:32 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/DataMapper.kt
> +        origin = this.origin?.toOriginModel() ?: OriginModel("", "", "", "", ""),
if object is of `null` type, we will not initialize it with empty data!

2024-11-11 05:32 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/DataMapper.kt
> +        episodes = this.episode.map { it!!.toEpisodeModel() }
never use `!!`

2024-11-11 05:32 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/DataMapper.kt
> +        type = this.type.orEmpty(),
`type` is nullable, so if there is no data let it be initialized as `null`

2024-11-11 11:35 UTC, shubhamsinghmutualmobile requested changes

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/DataMapper.kt
> +}
Isn't it an error to have a character without a unique ID? 🤔

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/DataMapper.kt
> +}
Same in both these cases 🤔

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +    override fun getCharactersList(): Flow<ResultState<List<CharactersListModel>>> = flow {
If the API is not returning the data in a subscription manner, then why are we consuming it in a `flow`? I believe showing states like `Loading` is a concern of the `presentation` layer and not `data`. We should make it a normal suspend function.

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +            emit(ResultState.Error(e))
Same here, no need for a flow

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on data/src/test/java/com/practical/data/CharacterRepositoryImplTest.kt
>              val repositoryWithMockApolloClient = CharacterRepositoryImpl(apolloClient)
Instead of using to `val`s, probably just create a single `var` and update it when needed.

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/usecases/GetCharacterUseCase.kt
> +    suspend fun getCharacters(id: String): Flow<ResultState<CharacterModel>> {
Better to use the same naming terminology everywhere. Since you're using the name `invoke` in other UseCases, it would be better to keep the naming consistent across all usecases.

2024-11-11 11:35 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +    private val defaultDispatcher: CoroutineDispatcher = Dispatchers.IO
Rename this to `coroutineDispatcher` instead

2024-11-11 12:50 UTC, shreyansh-mm approved these changes

2024-11-11 13:27 UTC, shubhamsinghmutualmobile approved these changes

2024-11-11 13:27 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/DataMapper.kt
> +    return this.id.let {
What does this logic do? `this.id.let`
It's not checking for `id`'s emptiness or nullability.
What exactly are we trying to do here?

2024-11-11 14:29 UTC, merged