Screen2
Vanshbajaj/Practical-Assignment pull request #21
Opened 2024-11-11 13:19 UTC by Vanshbajaj

1. Added DIspacter Module

2024-11-12 09:23 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/ViewModelFactory.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Rename it to `coroutineDispatcher`

2024-11-12 09:23 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/viewmodel/IoDispatcher.kt
No need for this qualifier

2024-11-12 09:24 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +            text = "EPISODES",
Extract string resource

2024-11-12 09:25 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    }
Prefer viewmodel's `init` block for such one-time initialisation operations. `LaunchedEffect` will fail in case of configuration changes.

2024-11-13 06:08 UTC, shreyansh-mm requested changes

2024-11-13 06:08 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharactersListScreen.kt
> +    onNavigateToCharacterScreen: (String, String) -> Unit = { characterId, characterName -> },
We don't need to initialize the lambda.

2024-11-13 06:08 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    Scaffold(
Scaffold should be used at root ideally. Move this to root and use app state to show / hide app bar.

2024-11-13 06:08 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +        )
Formatting

2024-11-13 06:08 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/DispatcherModule.kt
Let's add providers for other dispatchers

2024-11-13 06:08 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/IoDispatcher.kt
Create Qualifier for `DefaultDispatcher` and `MainDispatcher`

2024-11-13 06:08 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/ViewModelFactory.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Should be named as `coroutineDispatcher` unless we are injecting multiple different types of dispatchers.

2024-11-13 07:25 UTC, Vanshbajaj commented on presentation/src/main/java/com/practical/presentation/screens/CharactersListScreen.kt
> +    onNavigateToCharacterScreen: (String, String) -> Unit = { characterId, characterName -> },
/Users/vbajaj/AndroidStudioProjects/PracticalAssignment/presentation/src/main/java/com/practical/presentation/screens/CharactersListScreen.kt:38:5: Lambda parameters in a @Composable that are for events (e.g. onClick, onChange, etc) and are required (they don't have a default value) should not be used as the trailing parameter.

Composable functions that emit content usually reserve the trailing lambda syntax for the content slot, and that can lead to an assumption that other composables can be used in that lambda.

2024-11-15 06:24 UTC, shreyansh-mm requested changes

2024-11-15 06:24 UTC, shreyansh-mm commented on app/src/main/java/com/practical/assignment/AppNavGraph.kt
> +
Remove unnecessary code

2024-11-15 06:24 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    modifier: Modifier = Modifier,
Why is this modifier not being used / passed further?

2024-11-15 06:24 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    LaunchedEffect(characterId,modifier) { characterViewModel.getCharacter(characterId) }
Why does `LaunchedEffect` need `modifier` as key?

2024-11-15 06:24 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    when (state) {
Put this when inside a `Box` or `Column` or any composable

2024-11-15 06:24 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharactersListScreen.kt
> +        items(characters.size, key = { characters[it].id.orEmpty() }) { index ->
why is the key using `orEmpty()`?

2024-11-15 06:58 UTC, pushpalroygd commented on domain/src/main/java/com/practical/domain/CharactersListModel.kt
> +    val id: String?=null,
Can we format the code for all the files?

2024-11-15 06:58 UTC, pushpalroygd commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    characterViewModel: CharacterDetailsViewModel,
Do we need to pass the entire viewmodel here?

2024-11-15 07:11 UTC, Vanshbajaj commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    characterViewModel: CharacterDetailsViewModel,
yes it is required

2024-11-15 07:11 UTC, Vanshbajaj commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +    characterViewModel: CharacterDetailsViewModel,
yes

2024-11-18 04:50 UTC, shreyansh-mm approved these changes

2024-11-18 07:29 UTC, merged