Added Test Cases For Repository
Vanshbajaj/Practical-Assignment pull request #23
Opened 2024-11-15 14:13 UTC by Vanshbajaj

1. Added Test Cases For Repository

2024-11-18 04:55 UTC, shreyansh-mm requested changes

2024-11-18 04:55 UTC, shreyansh-mm commented on detekt.yml
> +    threshold: 70
This should remain 60

2024-11-19 05:46 UTC, shreyansh-mm requested changes

2024-11-19 05:46 UTC, shreyansh-mm commented on data/src/test/java/com/practical/data/CharacterRepositoryImplTest.kt
> +    """.trimIndent()
Since its just testing, lets trim down the JSON and response object to make this test more readable.

2024-11-22 07:34 UTC, shubhamsinghmutualmobile approved these changes

2024-11-25 04:18 UTC, merged