Screen3 data
Vanshbajaj/Practical-Assignment pull request #26
Opened 2024-11-26 07:11 UTC by Vanshbajaj

1. Added Data Layer
2. Added Domain Layer

2024-11-26 12:07 UTC, shreyansh-mm requested changes

2024-11-26 12:07 UTC, shreyansh-mm commented on domain/src/test/java/com/practical/domain/GetCharacterUseCaseTest.kt
Loading state should be consistently be emitted.

2024-11-27 11:49 UTC, shubhamsinghmutualmobile commented on data/src/main/graphql/EpsoideDetails.graphql
> +}
Let's only fetch data that we are actually displaying on-screen. For example, for the episode details screen, we only need the following data:

```graphql
query Episode($id: ID!) {
    episode(id: $id) {
        name
        air_date
        characters {
            id
            image
        }
    }
}
```

And please make sure to follow this approach for all your existing `graphql` files that might have not been reviewed as rigorously.

2024-11-27 11:51 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/EpsoideDataMapper.kt
> +        created = this.created
Let's make all `Character` fields nullable except `id` only.

2024-11-27 12:01 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +                    emit(ResultState.Error(Exception(Constants.error)))
The concept of `Loading`, `Success`, and `Failure` generally belongs to the `presentation` layer only. Hence, the `data` layer is only supposed/expected to just fetch the data from one or more sources.

At max, you may use the `data` layer to `catch-categorise-rethrow` exceptions/errors. For example:

```kotlin
override fun getEpisodeId(id: String): Flow<EpisodeModelDetails> {
    try {
      // Your logic here
    } catch (t: Throwable) {
      when (t) {
        is ClientNetworkException -> rethrow MessageException("Please check your network connection")
        is APIException -> rethrow MessageException("There was some issue with the data source")
        else -> rethrow MessageException("Unknown error occurred! Please try again later.")
      }
    }
}
```

2024-11-27 12:06 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +                    emit(ResultState.Error(Exception(Constants.error)))
In case of having to handle multiple languages, instead of creating a single `MessageException` class, create specific `*Exception` classes on the basis of which in the `presentation` layer, you can decide which `R.string.*` key to use from resources. For example:

```kotlin
override fun getEpisodeId(id: String): Flow<EpisodeModelDetails> {
    try {
      // Your logic here
    } catch (t: Throwable) {
      when (t) {
        is ClientNetworkException -> rethrow RMClientNetworkException
        is APIException -> rethrow RMAPIException
        else -> rethrow RMGeneralException
      }
    }
}
```

and in your `UI` code,

```kotlin
@Composable
fun <T> MyScreen(uiState: UIState<T>) {
   when (uiState) {
     is UIState.Error -> when (uiState.error) {
       is RMClientNetworkException -> Text("Some mobile network error happened")
       is RMAPIException -> Text("Some backend network error happened")
       else -> Text("An unknown exception occurred!")
     }
     else -> Text("MY SCREEN")
   }
}
```

2024-11-27 12:08 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/EpisodeModelDetails.kt
> +)
This class isn't doing anything and can be removed

2024-11-27 12:08 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/EpisodeModelDetails.kt
> +)
Same

2024-11-27 12:10 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/EpisodeModelDetails.kt
> +)
Try to re-use all model classes throughout the app wherever possible and every model class should have its own separate file

2024-11-27 12:12 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/repository/CharacterRepository.kt
> +    fun getEpisodeId(id: String): Flow<ResultState<EpisodeModelDetails>>
All these functions should be asynchronous, hence please make sure to prefix them with `suspend`

2024-11-27 12:13 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/usecases/GetCharactersUseCase.kt
> +    operator fun invoke() = repository.getCharactersList()
Revert this

2024-11-27 12:13 UTC, shubhamsinghmutualmobile commented on domain/src/test/java/com/practical/domain/GetCharacterByIdUseCaseTest.kt
Please write tests in a separate PR

2024-11-27 12:13 UTC, shubhamsinghmutualmobile commented on domain/src/test/java/com/practical/domain/GetCharactersUseCaseTest.kt
Same. Please write tests in a separate PR.

2024-11-27 12:14 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/practical/presentation/CharacterDetailsViewModelTest.kt
Same

2024-12-05 11:08 UTC, shreyansh-mm requested changes

2024-12-05 11:08 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/EpsoideDataMapper.kt
> +fun EpisodeQuery.Character.toCharacter(): Character {
private

2024-12-05 11:08 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/Character.kt
should be initialized with default value

2024-12-05 11:08 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/Episode.kt
should be initialized with default value

2024-12-05 11:08 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/EpisodeData.kt
should be initialized with default value

2024-12-05 11:08 UTC, shreyansh-mm commented on domain/src/main/java/com/practical/domain/EpisodeModelDetails.kt
should be initialized with default value

2024-12-11 11:53 UTC, shreyansh-mm approved these changes

2024-12-11 13:49 UTC, merged