Screen3 changes
Vanshbajaj/Practical-Assignment pull request #29
Opened 2024-11-28 16:47 UTC by Vanshbajaj

Feat - Added Ui State  in Presentation Layer
 
Handle the Expectations in Data Layer 
When the Internet is not connected
Internet is Connected

https://github.com/user-attachments/assets/c54bc55f-72c6-4693-a2e3-6ebc45b0bca9

2024-11-29 13:16 UTC, shreyansh-mm requested changes

2024-11-29 13:16 UTC, shreyansh-mm commented on data/src/test/java/com/practical/data/CharacterRepositoryImplTest.kt
> +
Lets remove the unnecessary spacing

2024-11-29 16:26 UTC, Vanshbajaj commented on data/src/main/java/com/practical/data/network/AppException.kt
> +class ApolloClientException : NetworkException()
singleton class cannot be extended

2024-12-02 12:23 UTC, shreyansh-mm requested changes

2024-12-02 12:23 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/network/NetworkException.kt
A lot of extra lines.

2024-12-02 12:23 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
> +            } ?: emptyList()
Why are we emitting empty list?

2024-12-02 12:23 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +        Column{
Why do we need a `Box` and `Column` both?

2024-12-03 04:06 UTC, shreyansh-mm requested changes

2024-12-03 12:27 UTC, shreyansh-mm requested changes

2024-12-03 12:27 UTC, shreyansh-mm commented on data/src/main/java/com/practical/data/repository/CharacterRepositoryImpl.kt
>          }
catch here is not needed

2024-12-03 12:27 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharactersListScreen.kt
> +                    }
same, you can reuse the composable made for above screen

2024-12-03 12:27 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/viewmodel/CharacterViewModel.kt
> +                }
This logic can be improved

2024-12-05 13:36 UTC, shreyansh-mm approved these changes
Migrate common composable out of CharacterSceen to its own file.

2024-12-09 10:03 UTC, merged