Character screen fixes
Vanshbajaj/Practical-Assignment pull request #36
Opened 2024-12-12 15:28 UTC by Vanshbajaj

2024-12-13 15:28 UTC, anmolsahi-mm commented on app/src/main/java/com/practical/assignment/AppNavGraph.kt
> +                navController.navigate(EpisodeScreenData(episodeId))
generally, I prefer named arguments, but that's a personal preference and depends on the project coding conventions too. Not a big deal.

2024-12-13 15:31 UTC, anmolsahi-mm commented on presentation/src/main/java/com/practical/presentation/screens/CharacterScreen.kt
> +        modifier = modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Start
can we put the parameters on separate lines?

2024-12-13 15:32 UTC, anmolsahi-mm commented on presentation/src/main/java/com/practical/presentation/screens/EspsoideDetailsScreen.kt
> +
If this is a WIP, could you please add a TODO here?

2024-12-14 13:29 UTC, sahianmol1 commented on presentation/src/main/java/com/practical/presentation/screens/EspsoideDetailsScreen.kt
> +
h

2024-12-16 13:15 UTC, shreyansh-mm requested changes

2024-12-16 13:15 UTC, shreyansh-mm commented on app/src/main/java/com/practical/assignment/MainActivity.kt
> +    lateinit var factory: EpisodeDetailsViewModelFactory
I don't think we need 2 factories

2024-12-16 13:15 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/common/CommonComposable.kt
> +fun ErrorText(message: Int, modifier: Modifier = Modifier) {
private

2024-12-16 13:15 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/common/CommonComposable.kt
Should be named as `ErrorComponents` or `ErrorUi`

2024-12-16 13:15 UTC, shreyansh-mm commented on presentation/src/main/java/com/practical/presentation/di/EpisodeDetailsViewModelFactory.kt
> +            checkNotNull(episodeId) { "Episode ID is missing" }
use requireNotNull

2024-12-23 19:29 UTC, shreyansh-mm approved these changes

2024-12-24 05:42 UTC, merged