Domain Layer Setup
Vanshbajaj/Practical-Assignment pull request #9
Opened 2024-10-21 12:30 UTC by Vanshbajaj

1. Added the GraphQl
2. Domain Layer Setup -Added UseCase, Repository
3. Made Common Lint Adding in the Project.gradle

2024-10-21 12:35 UTC, shubhamsinghmutualmobile requested changes

2024-10-21 12:35 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/repository/CharacterRepository.kt
> +    suspend fun getCharacters(): Flow<List<CharactersQuery.Data>>
Are you going to write a subscription for getting `CharactersQuery.Data`? If not, consider using `Flow`s only inside `ViewModel`s.

2024-10-21 12:35 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/practical/domain/usecases/GetCharactersUseCase.kt
> +class GetCharactersUseCase @Inject constructor(private val repository: CharacterRepository) {
Dependency injection components should not be a part of the `domain` layer. DI is a `presentation` layer concept.

2024-10-22 10:05 UTC, shubhamsinghmutualmobile commented on domain/build.gradle.kts
> +    }
You have written the same code thrice in 3 different modules. Can you try finding out a way to write this code only once and use it wherever you need?

2024-10-22 11:57 UTC, shubhamsinghmutualmobile commented on domain/build.gradle.kts
> +    }
Have you actually even resolved this comment?

2024-10-22 12:21 UTC, shubhamsinghshubham777 approved these changes

2024-10-22 12:27 UTC, shubhamsinghmutualmobile approved these changes

2024-10-22 12:32 UTC, merged